<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant</title>
    <link rel="stylesheet" href="./index.css" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&amp;display=swap" rel="stylesheet">
</head>

<body>
    <div class="container">
        <!--background image-->
        <div class="backgroundimage">
            <img src="./background.jpg" alt="rooms">
            <h1>Restaurant</h1>
        </div>
        <!--navbar-->
        <nav class="navBarContainer">
            <h1>Rolex</h1>
            <input type="checkbox" id="abc" />
            <label for="abc">
                <i class="fa-solid fa-bars menuIcon"></i>
            </label>
            <div class="subNav">
                <a href="D:\login360\Big Project/index.html">Home</a>
                <a href="./index.html">Restaurant</a>
                <a href="D:\login360\Big Project\rooms\index.html">Rooms</a>
                <a href="D:\login360\Big Project\Contact\index.html">Contact</a>
            </div>
        </nav>
        <!---Restaurant Title-->
        <div class="abc">
            <p>Restaurant</p>
            <h2>Hotel Master's Restaurant</h2>
        </div>
        <!---Food-->
        <section>
            <div class="item">
                <div class="box">
                    <div class="Img">
                        <img src="./photo/blooming-quesadilla-ring-1674080631.jpeg" alt="">
                    </div>
                    <div class="text">
                        <h1>Spiceal Deal</h1>
                    </div>
                    <div class="price">
                        <h4>Blooming Quesadilla Ring</h4>
                        <span>Price :<ins> ₹ 99.00</ins> </span>
                        <h3>Ratting: 4.5/5</h3>
                        <button class="order">Order Now</button>
                    </div>
                </div>
                <div class="box">
                    <div class="Img">
                        <img src="./photo/idly sambar.jpg" alt="">
                    </div>
                    <div class="text">
                        <h1>Food</h1>
                    </div>
                    <div class="price">
                        <h4>Idly Sambar</h4>
                        <span>Price :<ins> ₹ 99.00</ins> </span>
                        <h3>Ratting: 4.5/5</h3>
                        <button class="order">Order Now</button>
                    </div>
                </div>
                <div class="box">
                    <div class="Img">
                        <img src="./photo/taco soup.jpg" alt="">
                    </div>
                    <div class="text">
                        <h1>Food</h1>
                    </div>
                    <div class="price">
                        <h4>Taco Soup</h4>
                        <span>Price :<ins> ₹ 99.00</ins> </span>
                        <h3>Ratting: 4.5/5</h3>
                        <button class="order">Order Now</button>
                    </div>
                </div>
                <div class="box">
                    <div class="Img">
                        <img src="./photo/chargrilled_beef_rump_steaks-423aec1bd7327a3b7f5efb36784708e9.jpeg" alt="">
                    </div>
                    <div class="text">
                        <h1>Food</h1>
                    </div>
                    <div class="price">
                        <h4>Beef Rump</h4>
                        <span>Price :<ins> ₹ 99.00</ins> </span>
                        <h3>Ratting: 4.5/5</h3>
                        <button class="order">Order Now</button>
                    </div>
                </div>

            </div>

            <!---Food second-->
            <div class="item">
                <div class="box">
                    <div class="Img">
                        <img src="./photo/Cheesy-Mexican-Beef-and-Beans-Casserole_8a.webp" alt="">
                    </div>
                    <div class="text">
                        <h1>Spiceal Deal</h1>
                    </div>
                    <div class="price">
                        <h4>Mexican Beef</h4>
                        <span>Price :<ins> ₹ 99.00</ins> </span>
                        <h3>Ratting: 4.5/5</h3>
                        <button class="order">Order Now</button>
                    </div>
                </div>
                <div class="box">
                    <div class="Img">
                        <img src="./photo/chorizo-mozarella-gnocchi-bake-cropped-9ab73a3.jpg" alt="">
                    </div>
                    <div class="text">
                        <h1>Food</h1>
                    </div>
                    <div class="price">
                        <h4>Chorizo Mozarella</h4>
                        <span>Price :<ins> ₹ 99.00</ins> </span>
                        <h3>Ratting: 4.5/5</h3>
                        <button class="order">Order Now</button>
                    </div>
                </div>
                <div class="box">
                    <div class="Img">
                        <img src="./photo/parmesan-crumbed-chicken-schnitzel-fried-eggs-and-apple-cabbage-slaw-173352-2.jpg"
                            alt="">
                    </div>
                    <div class="text">
                        <h1>Food</h1>
                    </div>
                    <div class="price">
                        <h4>Parmesan Crumbed Chicken</h4>
                        <span>Price :<ins> ₹ 99.00</ins> </span>
                        <h3>Ratting: 4.5/5</h3>
                        <button class="order">Order Now</button>
                    </div>
                </div>
                <div class="box">
                    <div class="Img">
                        <img src="./photo/pexels-ash-376464.jpg" alt="">
                    </div>
                    <div class="text">
                        <h1>Food</h1>
                    </div>
                    <div class="price">
                        <h4>Pexels ash</h4>
                        <span>Price :<ins> ₹ 99.00</ins> </span>
                        <h3>Ratting: 4.5/5</h3>
                        <button class="order">Order Now</button>
                    </div>
                </div>

            </div>


        </section>
        <!--footer-->
        <footer>
            <div class="Footer">
                <h4>Company</h4>
                <p>About us</p>
                <p>Hotels</p>
                <p>Customer</p>
                <p>Contact us</p>
            </div>
            <div class="Footer ">
                <h4>Our Facilities</h4>
                <p>Restaurant</p>
                <p>Bar</p>
                <p>Pick up</p>
                <p>Swimming Pool</p>
                <p>GYM</p>
            </div>
            <div class="Footer">
                <h4>Subscribe</h4>
                <p>But the course is always on the same level. A large and large casino in the yeast.</p>
                <span>
                    <input class="email" type="text" id="zxc" placeholder="Enter Email Id"><label
                        for="zxc"><button>Send</button></label>
                </span>
            </div>
            <div class="Footer">
                <h4>Website</h4>
                <span>
                    <i class="fa-brands fa-instagram"></i>
                    <i class="fa-brands fa-facebook"></i>
                    <i class="fa-brands fa-twitter"></i>
                    <i class="fa-brands fa-github"></i>
                    <i class="fa-brands fa-linkedin"></i>
                </span>
            </div>
        </footer>


    </div>
</body>
